export const articleDatas = [{
  member: true,
  finish: false,
  name: '重生计划·时之卷',
  author: {
    name: 'SNH48',
    link: ''
  },
  articles: [
    {
      chapter: 1,
      title: '晨光',
      url: 'https://read.qidian.com/chapter/gunqLjJgXxGt-wSl2uB4dQ2/ME-Kbhi6zNPgn4SMoDUcDQ2'
    }, {
      chapter: 2,
      title: 'Forever 48',
      url: 'https://read.qidian.com/chapter/gunqLjJgXxGt-wSl2uB4dQ2/FTQsk4Xxwgtp4rPq4Fd4KQ2'
    }, {
      chapter: 3,
      title: 'Who is the one',
      url: 'https://read.qidian.com/chapter/gunqLjJgXxGt-wSl2uB4dQ2/VJ_4Qv8GqhJMs5iq0oQwLQ2'
    }, {
      chapter: 4,
      title: '黑洞',
      url: 'https://read.qidian.com/chapter/gunqLjJgXxGt-wSl2uB4dQ2/8tcJTl4MpLrwrjbX3WA1AA2'
    }, {
      chapter: 5,
      title: 'Flower',
      url: 'https://read.qidian.com/chapter/gunqLjJgXxGt-wSl2uB4dQ2/ywykl-eyp4v4p8iEw--PPw2'
    }, {
      chapter: 6,
      title: 'Hold me tight',
      url: 'https://read.qidian.com/chapter/gunqLjJgXxGt-wSl2uB4dQ2/sDI5ujN7LgHM5j8_3RRvhw2'
    }, {
      chapter: 7,
      title: '解语者',
      url: 'https://read.qidian.com/chapter/gunqLjJgXxGt-wSl2uB4dQ2/tl00-656l5ZMs5iq0oQwLQ2'
    }, {
      chapter: 8,
      title: 'Final round （上）',
      url: 'https://read.qidian.com/chapter/gunqLjJgXxGt-wSl2uB4dQ2/7zzRbHg806PwrjbX3WA1AA2'
    }, {
      chapter: 9,
      title: 'Final round （下）',
      url: 'https://read.qidian.com/chapter/gunqLjJgXxGt-wSl2uB4dQ2/n1Yfo-L5hpvwrjbX3WA1AA2'
    }, {
      chapter: 10,
      title: '无罪无我',
      url: 'https://read.qidian.com/chapter/gunqLjJgXxGt-wSl2uB4dQ2/EsxrtCKrxc3wrjbX3WA1AA2'
    }, {
      chapter: 11,
      title: 'Somewhere',
      url: 'https://read.qidian.com/chapter/gunqLjJgXxGt-wSl2uB4dQ2/kifydDoDhD9OBDFlr9quQA2'
    }, {
      chapter: 12,
      title: '发条舞者',
      url: 'https://read.qidian.com/chapter/gunqLjJgXxGt-wSl2uB4dQ2/vjLb9DkuKORp4rPq4Fd4KQ2'
    }, {
      chapter: 13,
      title: 'Restar',
      url: 'https://read.qidian.com/chapter/gunqLjJgXxGt-wSl2uB4dQ2/rb5HVSSmfcr6ItTi_ILQ7A2'
    }, {
      chapter: 14,
      title: '预言',
      url: 'https://read.qidian.com/chapter/gunqLjJgXxGt-wSl2uB4dQ2/fVawU8SHS6Xgn4SMoDUcDQ2'
    }, {
      chapter: 15,
      title: '彼岸花',
      url: 'https://read.qidian.com/chapter/gunqLjJgXxGt-wSl2uB4dQ2/bAeSkxTs4grwrjbX3WA1AA2'
    }, {
      chapter: 16,
      title: '重生计划',
      url: 'https://read.qidian.com/chapter/gunqLjJgXxGt-wSl2uB4dQ2/4ZPpl4UlEZxMs5iq0oQwLQ2'
    }, {
      chapter: 17,
      title: '坐标 121E 31N',
      url: 'https://read.qidian.com/chapter/gunqLjJgXxGt-wSl2uB4dQ2/4kOoFLh59KlOBDFlr9quQA2'
    }, {
      chapter: 18,
      title: '雪之国',
      url: 'https://read.qidian.com/chapter/gunqLjJgXxGt-wSl2uB4dQ2/Z_6wj9yponT4p8iEw--PPw2'
    }, {
      chapter: 19,
      title: '光明与黑暗',
      url: 'https://read.qidian.com/chapter/gunqLjJgXxGt-wSl2uB4dQ2/xggxK2yRmlpOBDFlr9quQA2'
    }, {
      chapter: 20,
      title: '命运齿轮',
      url: 'https://read.qidian.com/chapter/gunqLjJgXxGt-wSl2uB4dQ2/8To_60JyFg7M5j8_3RRvhw2'
    }, {
      chapter: 21,
      title: '十洲集结',
      url: 'https://read.qidian.com/chapter/gunqLjJgXxGt-wSl2uB4dQ2/axn2IPh54SxOBDFlr9quQA2'
    }, {
      chapter: 22,
      title: '画',
      url: 'https://read.qidian.com/chapter/gunqLjJgXxGt-wSl2uB4dQ2/PGzsj4bOimNMs5iq0oQwLQ2'
    }, {
      chapter: 23,
      title: '一体同心',
      url: 'https://read.qidian.com/chapter/gunqLjJgXxGt-wSl2uB4dQ2/CmQeI4-u5nLwrjbX3WA1AA2'
    }, {
      chapter: 24,
      title: '暗羽',
      url: 'https://read.qidian.com/chapter/gunqLjJgXxGt-wSl2uB4dQ2/pXe5_8EYmWTwrjbX3WA1AA2'
    }, {
      chapter: 25,
      title: '传颂之歌',
      url: 'https://read.qidian.com/chapter/gunqLjJgXxGt-wSl2uB4dQ2/7wP6gTUqmo3M5j8_3RRvhw2'
    }, {
      chapter: 26,
      title: '观自在',
      url: 'https://read.qidian.com/chapter/gunqLjJgXxGt-wSl2uB4dQ2/t_vVbyqJ687gn4SMoDUcDQ2'
    }, {
      chapter: 27,
      title: '信仰之箭',
      url: 'https://read.qidian.com/chapter/gunqLjJgXxGt-wSl2uB4dQ2/KYuQxrIPBeDgn4SMoDUcDQ2'
    }, {
      chapter: 28,
      title: '春日',
      url: 'https://read.qidian.com/chapter/gunqLjJgXxGt-wSl2uB4dQ2/9tK0yxn4V65OBDFlr9quQA2'
    }, {
      chapter: 29,
      title: '花之祭',
      url: 'https://read.qidian.com/chapter/gunqLjJgXxGt-wSl2uB4dQ2/ua7chJ2iMabwrjbX3WA1AA2'
    }, {
      chapter: 30,
      title: '时之卷',
      url: 'https://read.qidian.com/chapter/gunqLjJgXxGt-wSl2uB4dQ2/sN5sVVdzzhNMs5iq0oQwLQ2'
    }, {
      chapter: 31,
      title: '无尽的白',
      url: 'https://read.qidian.com/chapter/gunqLjJgXxGt-wSl2uB4dQ2/m8PS_-HdOoXgn4SMoDUcDQ2'
    }, {
      chapter: 32,
      title: '未知天空',
      url: 'https://read.qidian.com/chapter/gunqLjJgXxGt-wSl2uB4dQ2/2NRHslwQSjr6ItTi_ILQ7A2'
    }, {
      chapter: 33,
      title: '远方的海',
      url: 'https://read.qidian.com/chapter/gunqLjJgXxGt-wSl2uB4dQ2/NgbicsNVsn7gn4SMoDUcDQ2'
    }
  ]
}, {
  member: false,
  finish: false,
  name: '爱在校园',
  author: {
    name: 'Yours吟',
    link: ''
  },
  articles: [{
    chapter: 1,
    title: '1',
    url: 'https://www.bilibili.com/read/cv2898498'
  }, {
    chapter: 2,
    title: '2',
    url: 'https://www.bilibili.com/read/cv2912563'
  }, {
    chapter: 3,
    title: '3',
    url: 'https://www.bilibili.com/read/cv2929420'
  }, {
    chapter: 4,
    title: '4',
    url: 'https://www.bilibili.com/read/cv2935292'
  }, {
    chapter: 5,
    title: '5',
    url: 'https://www.bilibili.com/read/cv2949200'
  }, {
    chapter: 6,
    title: '6',
    url: 'https://www.bilibili.com/read/cv2961781'
  }, {
    chapter: 7,
    title: '7',
    url: 'https://www.bilibili.com/read/cv2974975'
  }, {
    chapter: 8,
    title: '8',
    url: 'https://www.bilibili.com/read/cv2982840'
  }, {
    chapter: 9,
    title: '9',
    url: 'https://www.bilibili.com/read/cv2994745'
  }]
}, {
  member: false,
  finish: true,
  name: '二十一',
  author: {
    name: '记忆里的三七',
    link: ''
  },
  articles: [{
    chapter: 1,
    title: '①',
    url: 'https://www.bilibili.com/read/cv2676175'
  }, {
    chapter: 2,
    title: '②',
    url: 'https://www.bilibili.com/read/cv2689382'
  }, {
    chapter: 3,
    title: '③',
    url: 'https://www.bilibili.com/read/cv2700787'
  }, {
    chapter: 4,
    title: '④',
    url: 'https://www.bilibili.com/read/cv2715077'
  }, {
    chapter: 5,
    title: '⑤',
    url: 'https://www.bilibili.com/read/cv2721123'
  }, {
    chapter: 6,
    title: '⑥',
    url: 'https://www.bilibili.com/read/cv2732903'
  }, {
    chapter: 7,
    title: '⑦',
    url: 'https://www.bilibili.com/read/cv2744429'
  }, {
    chapter: 8,
    title: '⑧',
    url: 'https://www.bilibili.com/read/cv2756975'
  }, {
    chapter: 9,
    title: '⑨',
    url: 'https://www.bilibili.com/read/cv2762746'
  }, {
    chapter: 10,
    title: '⑩',
    url: 'https://www.bilibili.com/read/cv2773446'
  }, {
    chapter: 11,
    title: '11',
    url: 'https://www.bilibili.com/read/cv2784133'
  }, {
    chapter: 12,
    title: '12',
    url: 'https://www.bilibili.com/read/cv2796033'
  }, {
    chapter: 13,
    title: '13',
    url: 'https://www.bilibili.com/read/cv2802575'
  }, {
    chapter: 14,
    title: '14',
    url: 'https://www.bilibili.com/read/cv2813490'
  }, {
    chapter: 15,
    title: '15',
    url: 'https://www.bilibili.com/read/cv2825151'
  }, {
    chapter: 16,
    title: '16',
    url: 'https://www.bilibili.com/read/cv2839955'
  }, {
    chapter: 17,
    title: '17',
    url: 'https://www.bilibili.com/read/cv2845906'
  }, {
    chapter: 18,
    title: '18',
    url: 'https://www.bilibili.com/read/cv2857118'
  }, {
    chapter: 19,
    title: '19',
    url: 'https://www.bilibili.com/read/cv2868678'
  }, {
    chapter: 20,
    title: '20',
    url: 'https://www.bilibili.com/read/cv2881480'
  }, {
    chapter: 21,
    title: '终章',
    url: 'https://www.bilibili.com/read/cv2886883'
  }]
}, {
  member: false,
  finish: false,
  name: '相忆深',
  author: {name: '', link: ''},
  articles: [{
    chapter: 1,
    title: '①',
    url: ''
  }, {
    chapter: 2,
    title: '②',
    url: ''
  }, {
    chapter: 3,
    title: '③',
    url: ''
  }, {
    chapter: 4,
    title: '④',
    url: ''
  }, {
    chapter: 5,
    title: '⑤',
    url: ''
  }, {
    chapter: 6,
    title: '⑥',
    url: ''
  }]
}, {
  member: false,
  finish: false,
  name: '孙芮的一天',
  author: {
    name: '不傲',
    link: ''
  },
  articles: [{
    chapter: 1,
    title: '①',
    url: 'https://www.bilibili.com/read/cv2360005'
  }, {
    chapter: 2,
    title: '②',
    url: 'https://www.bilibili.com/read/cv2367032'
  }, {
    chapter: 3,
    title: '③',
    url: 'https://www.bilibili.com/read/cv2378336'
  }, {
    chapter: 4,
    title: '④',
    url: 'https://www.bilibili.com/read/cv2413839'
  }, {
    chapter: 5,
    title: '⑤',
    url: 'https://www.bilibili.com/read/cv2438214'
  }, {
    chapter: 6,
    title: '⑥',
    url: 'https://www.bilibili.com/read/cv2460250'
  }]
}, {
  member: false,
  finish: false,
  name: '艾斯兔的琐事们',
  author: {
    name: '如Lee随行',
    link: ''
  },
  articles: [{
    chapter: 1,
    title: '(1)',
    url: 'https://www.bilibili.com/read/cv2360286'
  }, {
    chapter: 2,
    title: '(2)',
    url: 'https://www.bilibili.com/read/cv2390896'
  }, {
    chapter: 3,
    title: '(3)',
    url: 'https://www.bilibili.com/read/cv2407657'
  }, {
    chapter: 4,
    title: '(4)',
    url: 'https://www.bilibili.com/read/cv2426015'
  }, {
    chapter: 5,
    title: '(5)',
    url: 'https://www.bilibili.com/read/cv2453488'
  }, {
    chapter: 6,
    title: '(6)',
    url: 'https://www.bilibili.com/read/cv2473140'
  }, {
    chapter: 7,
    title: '(7)',
    url: 'https://www.bilibili.com/read/cv2485500'
  }, {
    chapter: 8,
    title: '(8)',
    url: 'https://www.bilibili.com/read/cv2500538'
  }, {
    chapter: 9,
    title: '(9)',
    url: 'https://www.bilibili.com/read/cv2506897'
  }, {
    chapter: 10,
    title: '(10)',
    url: 'https://www.bilibili.com/read/cv2519350'
  }, {
    chapter: 11,
    title: '(11)',
    url: 'https://www.bilibili.com/read/cv2529781'
  }, {
    chapter: 12,
    title: '番外',
    url: 'https://www.bilibili.com/read/cv2542404'
  }]
}, {
  member: false,
  finish: true,
  name: '重生计划-硝烟终奏',
  author: {
    name: '晓白鵺',
    link: 'https://weibo.com/u/6886194851'
  },
  articles: [{
    chapter: 1,
    title: '迷失',
    url: 'http://t.cn/EUrtCbR'
  }, {
    chapter: 2,
    title: '本质',
    url: 'http://t.cn/EUgEsE0'
  }, {
    chapter: 3,
    title: '人类',
    url: 'http://t.cn/EUkXmry'
  }, {
    chapter: 4,
    title: '交错',
    url: 'http://t.cn/E4PXPui'
  }, {
    chapter: 5,
    title: '失物',
    url: 'http://t.cn/E4z4Ylq'
  }, {
    chapter: 6,
    title: '宿命',
    url: 'http://t.cn/E4ANOau'
  }, {
    chapter: 7,
    title: '忽悠',
    url: 'http://t.cn/E4LcAE8'
  }, {
    chapter: 8,
    title: '交易',
    url: 'http://t.cn/E44v32F'
  }, {
    chapter: 9,
    title: '觉醒',
    url: 'http://t.cn/E4q59px'
  }, {
    chapter: 10,
    title: '拳击',
    url: 'http://t.cn/E4t6nrD'
  }, {
    chapter: 11,
    title: '再见',
    url: 'http://t.cn/E4fLN0l'
  }, {
    chapter: 12,
    title: '理由',
    url: 'http://t.cn/E4MVJu7'
  }, {
    chapter: 13,
    title: '暗杀',
    url: 'http://t.cn/E4X1OHl'
  }, {
    chapter: 14,
    title: 'somewhere',
    url: 'http://t.cn/E4S3tL2'
  }, {
    chapter: 15,
    title: '回溯',
    url: 'http://t.cn/E4p5C3o'
  }, {
    chapter: 16,
    title: '黑白对战（一）',
    url: 'http://t.cn/EfXBYjh'
  }, {
    chapter: 17,
    title: '黑白对战（二）',
    url: 'http://t.cn/Efpfas1'
  }, {
    chapter: 18,
    title: '黑白对战（三）',
    url: 'http://t.cn/EfQUYlr'
  }, {
    chapter: 19,
    title: '黑白对战（四）',
    url: 'http://t.cn/Ef1PDsT'
  }, {
    chapter: 20,
    title: '黑白对战（五）',
    url: 'http://t.cn/EfFmK8c'
  }, {
    chapter: 21,
    title: '黑白对战（六）',
    url: 'http://t.cn/EIA5z2s'
  }, {
    chapter: 22,
    title: '黑白对战（七）',
    url: 'http://t.cn/EIqnI9Y'
  }, {
    chapter: 23,
    title: '黑白对战（八）',
    url: 'http://t.cn/EIxxfBR'
  }, {
    chapter: 24,
    title: '黑白对战（九）',
    url: 'http://t.cn/EIKlva8'
  }, {
    chapter: 25,
    title: '黑白对战（十）',
    url: 'http://t.cn/EIj7l4Y'
  }, {
    chapter: 26,
    title: '黑白对战（十一）',
    url: 'http://t.cn/EIm7qDU'
  }, {
    chapter: 27,
    title: '黑白对战（十二）',
    url: 'http://t.cn/EIeRr4X'
  }, {
    chapter: 28,
    title: '黑白对战（十三）',
    url: 'http://t.cn/EMz9Wq5'
  }, {
    chapter: 29,
    title: '黑白对战（十四）',
    url: 'http://t.cn/EM43CLG'
  }, {
    chapter: 30,
    title: '黑白对战（十五）',
    url: 'http://t.cn/EMfy5DB'
  }, {
    chapter: 31,
    title: '黑白对战（十六）',
    url: 'http://t.cn/EMaxzuE'
  }, {
    chapter: 32,
    title: '致一年后的我们',
    url: 'http://t.cn/EMOUgQu'
  }, {
    chapter: 33,
    title: '守卫48区（一）',
    url: 'http://t.cn/EafDW8P'
  }, {
    chapter: 34,
    title: '守卫48区（二）',
    url: 'http://t.cn/Ea69J5I'
  }, {
    chapter: 35,
    title: '守卫48区（三）',
    url: 'http://t.cn/Eap92y4'
  }, {
    chapter: 36,
    title: '守卫48区（四）',
    url: 'http://t.cn/EaHDvgE'
  }, {
    chapter: 37,
    title: '守卫48区（五）',
    url: 'http://t.cn/Ea1VwVW'
  }, {
    chapter: 38,
    title: '守卫48区（六）',
    url: 'http://t.cn/EaFNUr7'
  }, {
    chapter: 39,
    title: '守卫48区（七）',
    url: 'http://t.cn/ESwdWEU'
  }, {
    chapter: 40,
    title: '守卫48区（八）',
    url: 'http://t.cn/ESqfpFS'
  }, {
    chapter: 41,
    title: '守卫48区（九）',
    url: 'http://t.cn/ESJfozS'
  }, {
    chapter: 42,
    title: '守卫48区（十）',
    url: 'http://t.cn/ESCcmS1'
  }, {
    chapter: 43,
    title: '守卫48区（十一）',
    url: 'http://t.cn/ESTvYeu'
  }, {
    chapter: 44,
    title: '守卫48区（十二）',
    url: 'http://t.cn/ESucDFD'
  }, {
    chapter: 45,
    title: '守卫48区（十三）',
    url: 'http://t.cn/ESD4I2u'
  }, {
    chapter: 46,
    title: '守卫48区（十四）',
    url: 'http://t.cn/Eo7lDyd'
  }, {
    chapter: 47,
    title: '战地记录',
    url: 'http://t.cn/Eo42P2V'
  }, {
    chapter: 48,
    title: '守卫48区（十五）',
    url: 'http://t.cn/EoIjMF3'
  }, {
    chapter: 49,
    title: '守卫48区（十六）',
    url: 'http://t.cn/EoKJoeF'
  }, {
    chapter: 50,
    title: '守卫48区（十七）',
    url: 'http://t.cn/Eojdmg7'
  }, {
    chapter: 51,
    title: '守卫48区（十八）',
    url: 'http://t.cn/Eom8jBh'
  }, {
    chapter: 52,
    title: '守卫48区（十九）',
    url: 'http://t.cn/EoDY4yd'
  }, {
    chapter: 53,
    title: '守卫48区（二十）',
    url: 'http://t.cn/EKzWaQC'
  }, {
    chapter: 54,
    title: '守卫48区（二十一）',
    url: 'http://t.cn/EKUD9sz'
  }, {
    chapter: 55,
    title: '守卫48区（二十二）',
    url: 'http://t.cn/EKVByAT'
  }, {
    chapter: 56,
    title: 'A视角',
    url: 'http://t.cn/AiOKSFWW'
  }, {
    chapter: 57,
    title: 'C视角',
    url: 'http://t.cn/AiOY5nHz'
  }, {
    chapter: 58,
    title: 'B视角',
    url: 'http://t.cn/AiO3x687'
  }, {
    chapter: 59,
    title: 'O视角',
    url: 'http://t.cn/AiOFkuhV'
  }, {
    chapter: 60,
    title: 'G视角',
    url: 'http://t.cn/AiW2DyLa'
  }, {
    chapter: 61,
    title: '主角',
    url: 'http://t.cn/AiWVxoiN'
  }, {
    chapter: 62,
    title: '完美犯罪（一）',
    url: 'http://t.cn/AiWa2heo'
  }, {
    chapter: 63,
    title: '完美犯罪（二）',
    url: 'http://t.cn/AiW01OqM'
  }, {
    chapter: 64,
    title: '完美犯罪（三）',
    url: 'http://t.cn/AiWRmhl7'
  }, {
    chapter: 65,
    title: '完美犯罪（四）',
    url: 'http://t.cn/AiWddvVb'
  }, {
    chapter: 66,
    title: '完美犯罪（五）',
    url: 'http://t.cn/Ail7vHLk'
  }, {
    chapter: 67,
    title: '无法逃离（一）',
    url: 'http://t.cn/Ail4x1nW'
  }, {
    chapter: 68,
    title: '无法逃离（二）',
    url: 'http://t.cn/AilMcusC'
  }, {
    chapter: 69,
    title: '无法逃离（三）',
    url: 'http://t.cn/AilK43Kg'
  }]
}, {
  member: true,
  finish: true,
  name: '杀手的故事',
  author: {
    name: 'SNH48-莫寒',
    link: 'https://weibo.com/momo0v03'
  },
  articles: [{
    chapter: 1,
    title: '杀手的故事（一）',
    url: 'http://t.cn/EyqPKtc'
  }, {
    chapter: 2,
    title: '杀手的故事（二）',
    url: 'http://t.cn/EyMdurK'
  }, {
    chapter: 3,
    title: '杀手的故事（三）',
    url: 'http://t.cn/EUnxdsx'
  }, {
    chapter: 4,
    title: '杀手的故事（四）',
    url: 'http://t.cn/E4AAmmb'
  }]
}, {
  member: true,
  finish: true,
  name: '《重生计划》小说中对应成员解析',
  author: {
    name: 'SNH48-袁丹妮',
    link: 'https://weibo.com/u/5225886388'
  },
  articles: [{
    chapter: 1,
    title: '（一） 莫寒，钱蓓婷，李宇琪，袁雨桢',
    url: 'http://t.cn/ELveNdQ'
  }, {
    chapter: 2,
    title: '（二） 吴哲晗，孙芮，徐子轩',
    url: 'http://t.cn/ELzexbG'
  }, {
    chapter: 3,
    title: '（三） 戴萌，孔肖吟，许佳琪',
    url: 'http://t.cn/ELUn7me'
  }, {
    chapter: 4,
    title: '（四） 莫寒，刘增艳，陈观慧',
    url: 'http://t.cn/EL6YVnZ'
  }, {
    chapter: 5,
    title: '（五） 张语格，邵雪聪，吕一，陈思，徐晨辰，蒋芸',
    url: 'http://t.cn/ELjSbHO'
  }]
}]
