export const articleDatas = [{
  member: false,
  finish: true,
  name: '重生计划-硝烟终奏',
  author: {
    name: '晓白鵺',
    link: 'https://weibo.com/u/6886194851'
  },
  articles: [{
    chapter: 1,
    title: '迷失',
    url: 'http://t.cn/EUrtCbR'
  }, {
    chapter: 2,
    title: '本质',
    url: 'http://t.cn/EUgEsE0'
  }, {
    chapter: 3,
    title: '人类',
    url: 'http://t.cn/EUkXmry'
  }, {
    chapter: 4,
    title: '交错',
    url: 'http://t.cn/E4PXPui'
  }, {
    chapter: 5,
    title: '失物',
    url: 'http://t.cn/E4z4Ylq'
  }, {
    chapter: 6,
    title: '宿命',
    url: 'http://t.cn/E4ANOau'
  }, {
    chapter: 7,
    title: '忽悠',
    url: 'http://t.cn/E4LcAE8'
  }, {
    chapter: 8,
    title: '交易',
    url: 'http://t.cn/E44v32F'
  }, {
    chapter: 9,
    title: '觉醒',
    url: 'http://t.cn/E4q59px'
  }, {
    chapter: 10,
    title: '拳击',
    url: 'http://t.cn/E4t6nrD'
  }, {
    chapter: 11,
    title: '再见',
    url: 'http://t.cn/E4fLN0l'
  }, {
    chapter: 12,
    title: '理由',
    url: 'http://t.cn/E4MVJu7'
  }, {
    chapter: 13,
    title: '暗杀',
    url: 'http://t.cn/E4X1OHl'
  }, {
    chapter: 14,
    title: 'somewhere',
    url: 'http://t.cn/E4S3tL2'
  }, {
    chapter: 15,
    title: '回溯',
    url: 'http://t.cn/E4p5C3o'
  }, {
    chapter: 16,
    title: '黑白对战（一）',
    url: 'http://t.cn/EfXBYjh'
  }, {
    chapter: 17,
    title: '黑白对战（二）',
    url: 'http://t.cn/Efpfas1'
  }, {
    chapter: 18,
    title: '黑白对战（三）',
    url: 'http://t.cn/EfQUYlr'
  }, {
    chapter: 19,
    title: '黑白对战（四）',
    url: 'http://t.cn/Ef1PDsT'
  }, {
    chapter: 20,
    title: '黑白对战（五）',
    url: 'http://t.cn/EfFmK8c'
  }, {
    chapter: 21,
    title: '黑白对战（六）',
    url: 'http://t.cn/EIA5z2s'
  }, {
    chapter: 22,
    title: '黑白对战（七）',
    url: 'http://t.cn/EIqnI9Y'
  }, {
    chapter: 23,
    title: '黑白对战（八）',
    url: 'http://t.cn/EIxxfBR'
  }, {
    chapter: 24,
    title: '黑白对战（九）',
    url: 'http://t.cn/EIKlva8'
  }, {
    chapter: 25,
    title: '黑白对战（十）',
    url: 'http://t.cn/EIj7l4Y'
  }, {
    chapter: 26,
    title: '黑白对战（十一）',
    url: 'http://t.cn/EIm7qDU'
  }, {
    chapter: 27,
    title: '黑白对战（十二）',
    url: 'http://t.cn/EIeRr4X'
  }, {
    chapter: 28,
    title: '黑白对战（十三）',
    url: 'http://t.cn/EMz9Wq5'
  }, {
    chapter: 29,
    title: '黑白对战（十四）',
    url: 'http://t.cn/EM43CLG'
  }, {
    chapter: 30,
    title: '黑白对战（十五）',
    url: 'http://t.cn/EMfy5DB'
  }, {
    chapter: 31,
    title: '黑白对战（十六）',
    url: 'http://t.cn/EMaxzuE'
  }, {
    chapter: 32,
    title: '致一年后的我们',
    url: 'http://t.cn/EMOUgQu'
  }]
}, {
  member: true,
  finish: true,
  name: '杀手的故事',
  author: {
    name: 'SNH48-莫寒',
    link: 'https://weibo.com/momo0v03'
  },
  articles: [{
    chapter: 1,
    title: '杀手的故事（一）',
    url: 'http://t.cn/EyqPKtc'
  }, {
    chapter: 2,
    title: '杀手的故事（二）',
    url: 'http://t.cn/EyMdurK'
  }, {
    chapter: 3,
    title: '杀手的故事（三）',
    url: 'http://t.cn/EUnxdsx'
  }, {
    chapter: 4,
    title: '杀手的故事（四）',
    url: 'http://t.cn/E4AAmmb'
  }]
}, {
  member: true,
  finish: true,
  name: '《重生计划》小说中对应成员解析',
  author: {
    name: 'SNH48-袁丹妮',
    link: 'https://weibo.com/u/5225886388'
  },
  articles: [{
    chapter: 1,
    title: '（一） 莫寒，钱蓓婷，李宇琪，袁雨桢',
    url: 'http://t.cn/ELveNdQ'
  }, {
    chapter: 2,
    title: '（二） 吴哲晗，孙芮，徐子轩',
    url: 'http://t.cn/ELzexbG'
  }, {
    chapter: 3,
    title: '（三） 戴萌，孔肖吟，许佳琪',
    url: 'http://t.cn/ELUn7me'
  }, {
    chapter: 4,
    title: '（四） 莫寒，刘增艳，陈观慧',
    url: 'http://t.cn/EL6YVnZ'
  }, {
    chapter: 5,
    title: '（五） 张语格，邵雪聪，吕一，陈思，徐晨辰，蒋芸',
    url: 'http://t.cn/ELjSbHO'
  }]
}]
